[build]
# Install Python dependencies
command = "cd backend && pip install -r requirements.txt"

[run]
# Command to start your FastAPI application
command = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[env]
# Required environment variables
GITHUB_APP_ID = ""
GITHUB_APP_PRIVATE_KEY = ""
GITHUB_WEBHOOK_SECRET = ""
SLACK_BOT_TOKEN = ""
SLACK_SIGNING_SECRET = ""
DATABASE_URL = ""
SECRET_KEY = ""

[build.environment]
# Python version
PYTHON_VERSION = "3.9"

[deploy]
# Auto-deploy on push to main branch
auto_deploy = true
branch = "main"

[health]
# Health check endpoint
path = "/health"
timeout = 30
interval = 60

[builds]
# Build cache settings
cache = true

[builds.caches]
# Cache Python dependencies
- "~/.cache/pip"
- "/opt/buildhome/.cache/pip"

[[redirects]]
# Redirect all traffic to HTTPS
from = "/*"
to = "/"
status = 200
force = true

[[headers]]
# Security headers
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
